# Generated by Django 5.0.6 on 2024-05-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Availibity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='Publication_year',
            field=models.IntegerField(null=True),
        ),
    ]
